//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Antler/antler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="antlerParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IantlerListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] antlerParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] antlerParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.whileStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStmt([NotNull] antlerParser.WhileStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.whileStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStmt([NotNull] antlerParser.WhileStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.logicalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalExpr([NotNull] antlerParser.LogicalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.logicalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalExpr([NotNull] antlerParser.LogicalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.disjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisjunction([NotNull] antlerParser.DisjunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.disjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisjunction([NotNull] antlerParser.DisjunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConjunction([NotNull] antlerParser.ConjunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConjunction([NotNull] antlerParser.ConjunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.negation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegation([NotNull] antlerParser.NegationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.negation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegation([NotNull] antlerParser.NegationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] antlerParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] antlerParser.PrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] antlerParser.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] antlerParser.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.cmpOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmpOp([NotNull] antlerParser.CmpOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.cmpOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmpOp([NotNull] antlerParser.CmpOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] antlerParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] antlerParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.stmtList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtList([NotNull] antlerParser.StmtListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.stmtList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtList([NotNull] antlerParser.StmtListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt([NotNull] antlerParser.StmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt([NotNull] antlerParser.StmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.assignmentStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentStmt([NotNull] antlerParser.AssignmentStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.assignmentStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentStmt([NotNull] antlerParser.AssignmentStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.assignOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignOp([NotNull] antlerParser.AssignOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.assignOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignOp([NotNull] antlerParser.AssignOpContext context);
}
