//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from antler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class antlerParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, ID=23, INT=24, WS=25, 
		AND=26, OR=27;
	public const int
		RULE_program = 0, RULE_operatorWhile = 1, RULE_stmtList = 2, RULE_statement = 3, 
		RULE_assignStmt = 4, RULE_assignOp = 5, RULE_logicalExpr = 6, RULE_orExpr = 7, 
		RULE_orTail = 8, RULE_andExpr = 9, RULE_andTail = 10, RULE_relExpr = 11, 
		RULE_relTail = 12, RULE_relOp = 13, RULE_addExpr = 14, RULE_addTail = 15, 
		RULE_mulExpr = 16, RULE_mulTail = 17, RULE_factor = 18;
	public static readonly string[] ruleNames = {
		"program", "operatorWhile", "stmtList", "statement", "assignStmt", "assignOp", 
		"logicalExpr", "orExpr", "orTail", "andExpr", "andTail", "relExpr", "relTail", 
		"relOp", "addExpr", "addTail", "mulExpr", "mulTail", "factor"
	};

	private static readonly string[] _LiteralNames = {
		null, "'while'", "':'", "';'", "'='", "'+='", "'-='", "'*='", "'/='", 
		"'<'", "'>'", "'<='", "'>='", "'=='", "'!='", "'+'", "'-'", "'*'", "'/'", 
		"'('", "')'", "'not'", "'!'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, "ID", 
		"INT", "WS", "AND", "OR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "antler.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static antlerParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public antlerParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public antlerParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OperatorWhileContext operatorWhile() {
			return GetRuleContext<OperatorWhileContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(antlerParser.Eof, 0); }
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 38;
			operatorWhile();
			State = 39;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperatorWhileContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtListContext stmtList() {
			return GetRuleContext<StmtListContext>(0);
		}
		public OperatorWhileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operatorWhile; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterOperatorWhile(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitOperatorWhile(this);
		}
	}

	[RuleVersion(0)]
	public OperatorWhileContext operatorWhile() {
		OperatorWhileContext _localctx = new OperatorWhileContext(Context, State);
		EnterRule(_localctx, 2, RULE_operatorWhile);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 41;
			Match(T__0);
			State = 42;
			logicalExpr();
			State = 43;
			Match(T__1);
			State = 45;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
			case 1:
				{
				State = 44;
				stmtList();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StmtListContext stmtList() {
			return GetRuleContext<StmtListContext>(0);
		}
		public StmtListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmtList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterStmtList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitStmtList(this);
		}
	}

	[RuleVersion(0)]
	public StmtListContext stmtList() {
		StmtListContext _localctx = new StmtListContext(Context, State);
		EnterRule(_localctx, 4, RULE_stmtList);
		try {
			State = 51;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__18:
			case T__20:
			case T__21:
			case ID:
			case INT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 47;
				statement();
				State = 48;
				stmtList();
				}
				break;
			case Eof:
				EnterOuterAlt(_localctx, 2);
				{
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AssignStmtContext assignStmt() {
			return GetRuleContext<AssignStmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 6, RULE_statement);
		try {
			State = 57;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 53;
				assignStmt();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 54;
				logicalExpr();
				State = 55;
				Match(T__2);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignStmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(antlerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public AssignOpContext assignOp() {
			return GetRuleContext<AssignOpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		public AssignStmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignStmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterAssignStmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitAssignStmt(this);
		}
	}

	[RuleVersion(0)]
	public AssignStmtContext assignStmt() {
		AssignStmtContext _localctx = new AssignStmtContext(Context, State);
		EnterRule(_localctx, 8, RULE_assignStmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 59;
			Match(ID);
			State = 60;
			assignOp();
			State = 61;
			logicalExpr();
			State = 62;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignOpContext : ParserRuleContext {
		public AssignOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterAssignOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitAssignOp(this);
		}
	}

	[RuleVersion(0)]
	public AssignOpContext assignOp() {
		AssignOpContext _localctx = new AssignOpContext(Context, State);
		EnterRule(_localctx, 10, RULE_assignOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 64;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 496L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OrExprContext orExpr() {
			return GetRuleContext<OrExprContext>(0);
		}
		public LogicalExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterLogicalExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitLogicalExpr(this);
		}
	}

	[RuleVersion(0)]
	public LogicalExprContext logicalExpr() {
		LogicalExprContext _localctx = new LogicalExprContext(Context, State);
		EnterRule(_localctx, 12, RULE_logicalExpr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 66;
			orExpr();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OrExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AndExprContext andExpr() {
			return GetRuleContext<AndExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OrTailContext orTail() {
			return GetRuleContext<OrTailContext>(0);
		}
		public OrExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_orExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterOrExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitOrExpr(this);
		}
	}

	[RuleVersion(0)]
	public OrExprContext orExpr() {
		OrExprContext _localctx = new OrExprContext(Context, State);
		EnterRule(_localctx, 14, RULE_orExpr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 68;
			andExpr();
			State = 69;
			orTail();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OrTailContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR() { return GetToken(antlerParser.OR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public AndExprContext andExpr() {
			return GetRuleContext<AndExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OrTailContext orTail() {
			return GetRuleContext<OrTailContext>(0);
		}
		public OrTailContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_orTail; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterOrTail(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitOrTail(this);
		}
	}

	[RuleVersion(0)]
	public OrTailContext orTail() {
		OrTailContext _localctx = new OrTailContext(Context, State);
		EnterRule(_localctx, 16, RULE_orTail);
		try {
			State = 76;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OR:
				EnterOuterAlt(_localctx, 1);
				{
				State = 71;
				Match(OR);
				State = 72;
				andExpr();
				State = 73;
				orTail();
				}
				break;
			case T__1:
			case T__2:
			case T__19:
				EnterOuterAlt(_localctx, 2);
				{
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AndExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RelExprContext relExpr() {
			return GetRuleContext<RelExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AndTailContext andTail() {
			return GetRuleContext<AndTailContext>(0);
		}
		public AndExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_andExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterAndExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitAndExpr(this);
		}
	}

	[RuleVersion(0)]
	public AndExprContext andExpr() {
		AndExprContext _localctx = new AndExprContext(Context, State);
		EnterRule(_localctx, 18, RULE_andExpr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 78;
			relExpr();
			State = 79;
			andTail();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AndTailContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND() { return GetToken(antlerParser.AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public RelExprContext relExpr() {
			return GetRuleContext<RelExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AndTailContext andTail() {
			return GetRuleContext<AndTailContext>(0);
		}
		public AndTailContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_andTail; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterAndTail(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitAndTail(this);
		}
	}

	[RuleVersion(0)]
	public AndTailContext andTail() {
		AndTailContext _localctx = new AndTailContext(Context, State);
		EnterRule(_localctx, 20, RULE_andTail);
		try {
			State = 86;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case AND:
				EnterOuterAlt(_localctx, 1);
				{
				State = 81;
				Match(AND);
				State = 82;
				relExpr();
				State = 83;
				andTail();
				}
				break;
			case T__1:
			case T__2:
			case T__19:
			case OR:
				EnterOuterAlt(_localctx, 2);
				{
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AddExprContext addExpr() {
			return GetRuleContext<AddExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelTailContext relTail() {
			return GetRuleContext<RelTailContext>(0);
		}
		public RelExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterRelExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitRelExpr(this);
		}
	}

	[RuleVersion(0)]
	public RelExprContext relExpr() {
		RelExprContext _localctx = new RelExprContext(Context, State);
		EnterRule(_localctx, 22, RULE_relExpr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88;
			addExpr();
			State = 89;
			relTail();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelTailContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RelOpContext relOp() {
			return GetRuleContext<RelOpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AddExprContext addExpr() {
			return GetRuleContext<AddExprContext>(0);
		}
		public RelTailContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relTail; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterRelTail(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitRelTail(this);
		}
	}

	[RuleVersion(0)]
	public RelTailContext relTail() {
		RelTailContext _localctx = new RelTailContext(Context, State);
		EnterRule(_localctx, 24, RULE_relTail);
		try {
			State = 95;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__8:
			case T__9:
			case T__10:
			case T__11:
			case T__12:
			case T__13:
				EnterOuterAlt(_localctx, 1);
				{
				State = 91;
				relOp();
				State = 92;
				addExpr();
				}
				break;
			case T__1:
			case T__2:
			case T__19:
			case AND:
			case OR:
				EnterOuterAlt(_localctx, 2);
				{
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelOpContext : ParserRuleContext {
		public RelOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterRelOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitRelOp(this);
		}
	}

	[RuleVersion(0)]
	public RelOpContext relOp() {
		RelOpContext _localctx = new RelOpContext(Context, State);
		EnterRule(_localctx, 26, RULE_relOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 97;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 32256L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AddExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MulExprContext mulExpr() {
			return GetRuleContext<MulExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AddTailContext addTail() {
			return GetRuleContext<AddTailContext>(0);
		}
		public AddExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_addExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterAddExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitAddExpr(this);
		}
	}

	[RuleVersion(0)]
	public AddExprContext addExpr() {
		AddExprContext _localctx = new AddExprContext(Context, State);
		EnterRule(_localctx, 28, RULE_addExpr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 99;
			mulExpr();
			State = 100;
			addTail();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AddTailContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MulExprContext mulExpr() {
			return GetRuleContext<MulExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AddTailContext addTail() {
			return GetRuleContext<AddTailContext>(0);
		}
		public AddTailContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_addTail; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterAddTail(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitAddTail(this);
		}
	}

	[RuleVersion(0)]
	public AddTailContext addTail() {
		AddTailContext _localctx = new AddTailContext(Context, State);
		EnterRule(_localctx, 30, RULE_addTail);
		try {
			State = 111;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__14:
				EnterOuterAlt(_localctx, 1);
				{
				State = 102;
				Match(T__14);
				State = 103;
				mulExpr();
				State = 104;
				addTail();
				}
				break;
			case T__15:
				EnterOuterAlt(_localctx, 2);
				{
				State = 106;
				Match(T__15);
				State = 107;
				mulExpr();
				State = 108;
				addTail();
				}
				break;
			case T__1:
			case T__2:
			case T__8:
			case T__9:
			case T__10:
			case T__11:
			case T__12:
			case T__13:
			case T__19:
			case AND:
			case OR:
				EnterOuterAlt(_localctx, 3);
				{
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MulExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FactorContext factor() {
			return GetRuleContext<FactorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MulTailContext mulTail() {
			return GetRuleContext<MulTailContext>(0);
		}
		public MulExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mulExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterMulExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitMulExpr(this);
		}
	}

	[RuleVersion(0)]
	public MulExprContext mulExpr() {
		MulExprContext _localctx = new MulExprContext(Context, State);
		EnterRule(_localctx, 32, RULE_mulExpr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 113;
			factor();
			State = 114;
			mulTail();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MulTailContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FactorContext factor() {
			return GetRuleContext<FactorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MulTailContext mulTail() {
			return GetRuleContext<MulTailContext>(0);
		}
		public MulTailContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mulTail; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterMulTail(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitMulTail(this);
		}
	}

	[RuleVersion(0)]
	public MulTailContext mulTail() {
		MulTailContext _localctx = new MulTailContext(Context, State);
		EnterRule(_localctx, 34, RULE_mulTail);
		try {
			State = 125;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__16:
				EnterOuterAlt(_localctx, 1);
				{
				State = 116;
				Match(T__16);
				State = 117;
				factor();
				State = 118;
				mulTail();
				}
				break;
			case T__17:
				EnterOuterAlt(_localctx, 2);
				{
				State = 120;
				Match(T__17);
				State = 121;
				factor();
				State = 122;
				mulTail();
				}
				break;
			case T__1:
			case T__2:
			case T__8:
			case T__9:
			case T__10:
			case T__11:
			case T__12:
			case T__13:
			case T__14:
			case T__15:
			case T__19:
			case AND:
			case OR:
				EnterOuterAlt(_localctx, 3);
				{
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FactorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(antlerParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(antlerParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FactorContext factor() {
			return GetRuleContext<FactorContext>(0);
		}
		public FactorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_factor; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.EnterFactor(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IantlerListener typedListener = listener as IantlerListener;
			if (typedListener != null) typedListener.ExitFactor(this);
		}
	}

	[RuleVersion(0)]
	public FactorContext factor() {
		FactorContext _localctx = new FactorContext(Context, State);
		EnterRule(_localctx, 36, RULE_factor);
		try {
			State = 137;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 127;
				Match(ID);
				}
				break;
			case INT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 128;
				Match(INT);
				}
				break;
			case T__18:
				EnterOuterAlt(_localctx, 3);
				{
				State = 129;
				Match(T__18);
				State = 130;
				logicalExpr();
				State = 131;
				Match(T__19);
				}
				break;
			case T__20:
				EnterOuterAlt(_localctx, 4);
				{
				State = 133;
				Match(T__20);
				State = 134;
				factor();
				}
				break;
			case T__21:
				EnterOuterAlt(_localctx, 5);
				{
				State = 135;
				Match(T__21);
				State = 136;
				factor();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,27,140,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,1,0,1,0,1,0,1,1,1,1,1,1,1,1,3,
		1,46,8,1,1,2,1,2,1,2,1,2,3,2,52,8,2,1,3,1,3,1,3,1,3,3,3,58,8,3,1,4,1,4,
		1,4,1,4,1,4,1,5,1,5,1,6,1,6,1,7,1,7,1,7,1,8,1,8,1,8,1,8,1,8,3,8,77,8,8,
		1,9,1,9,1,9,1,10,1,10,1,10,1,10,1,10,3,10,87,8,10,1,11,1,11,1,11,1,12,
		1,12,1,12,1,12,3,12,96,8,12,1,13,1,13,1,14,1,14,1,14,1,15,1,15,1,15,1,
		15,1,15,1,15,1,15,1,15,1,15,3,15,112,8,15,1,16,1,16,1,16,1,17,1,17,1,17,
		1,17,1,17,1,17,1,17,1,17,1,17,3,17,126,8,17,1,18,1,18,1,18,1,18,1,18,1,
		18,1,18,1,18,1,18,1,18,3,18,138,8,18,1,18,0,0,19,0,2,4,6,8,10,12,14,16,
		18,20,22,24,26,28,30,32,34,36,0,2,1,0,4,8,1,0,9,14,134,0,38,1,0,0,0,2,
		41,1,0,0,0,4,51,1,0,0,0,6,57,1,0,0,0,8,59,1,0,0,0,10,64,1,0,0,0,12,66,
		1,0,0,0,14,68,1,0,0,0,16,76,1,0,0,0,18,78,1,0,0,0,20,86,1,0,0,0,22,88,
		1,0,0,0,24,95,1,0,0,0,26,97,1,0,0,0,28,99,1,0,0,0,30,111,1,0,0,0,32,113,
		1,0,0,0,34,125,1,0,0,0,36,137,1,0,0,0,38,39,3,2,1,0,39,40,5,0,0,1,40,1,
		1,0,0,0,41,42,5,1,0,0,42,43,3,12,6,0,43,45,5,2,0,0,44,46,3,4,2,0,45,44,
		1,0,0,0,45,46,1,0,0,0,46,3,1,0,0,0,47,48,3,6,3,0,48,49,3,4,2,0,49,52,1,
		0,0,0,50,52,1,0,0,0,51,47,1,0,0,0,51,50,1,0,0,0,52,5,1,0,0,0,53,58,3,8,
		4,0,54,55,3,12,6,0,55,56,5,3,0,0,56,58,1,0,0,0,57,53,1,0,0,0,57,54,1,0,
		0,0,58,7,1,0,0,0,59,60,5,23,0,0,60,61,3,10,5,0,61,62,3,12,6,0,62,63,5,
		3,0,0,63,9,1,0,0,0,64,65,7,0,0,0,65,11,1,0,0,0,66,67,3,14,7,0,67,13,1,
		0,0,0,68,69,3,18,9,0,69,70,3,16,8,0,70,15,1,0,0,0,71,72,5,27,0,0,72,73,
		3,18,9,0,73,74,3,16,8,0,74,77,1,0,0,0,75,77,1,0,0,0,76,71,1,0,0,0,76,75,
		1,0,0,0,77,17,1,0,0,0,78,79,3,22,11,0,79,80,3,20,10,0,80,19,1,0,0,0,81,
		82,5,26,0,0,82,83,3,22,11,0,83,84,3,20,10,0,84,87,1,0,0,0,85,87,1,0,0,
		0,86,81,1,0,0,0,86,85,1,0,0,0,87,21,1,0,0,0,88,89,3,28,14,0,89,90,3,24,
		12,0,90,23,1,0,0,0,91,92,3,26,13,0,92,93,3,28,14,0,93,96,1,0,0,0,94,96,
		1,0,0,0,95,91,1,0,0,0,95,94,1,0,0,0,96,25,1,0,0,0,97,98,7,1,0,0,98,27,
		1,0,0,0,99,100,3,32,16,0,100,101,3,30,15,0,101,29,1,0,0,0,102,103,5,15,
		0,0,103,104,3,32,16,0,104,105,3,30,15,0,105,112,1,0,0,0,106,107,5,16,0,
		0,107,108,3,32,16,0,108,109,3,30,15,0,109,112,1,0,0,0,110,112,1,0,0,0,
		111,102,1,0,0,0,111,106,1,0,0,0,111,110,1,0,0,0,112,31,1,0,0,0,113,114,
		3,36,18,0,114,115,3,34,17,0,115,33,1,0,0,0,116,117,5,17,0,0,117,118,3,
		36,18,0,118,119,3,34,17,0,119,126,1,0,0,0,120,121,5,18,0,0,121,122,3,36,
		18,0,122,123,3,34,17,0,123,126,1,0,0,0,124,126,1,0,0,0,125,116,1,0,0,0,
		125,120,1,0,0,0,125,124,1,0,0,0,126,35,1,0,0,0,127,138,5,23,0,0,128,138,
		5,24,0,0,129,130,5,19,0,0,130,131,3,12,6,0,131,132,5,20,0,0,132,138,1,
		0,0,0,133,134,5,21,0,0,134,138,3,36,18,0,135,136,5,22,0,0,136,138,3,36,
		18,0,137,127,1,0,0,0,137,128,1,0,0,0,137,129,1,0,0,0,137,133,1,0,0,0,137,
		135,1,0,0,0,138,37,1,0,0,0,9,45,51,57,76,86,95,111,125,137
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
