//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from antler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IantlerListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class antlerBaseListener : IantlerListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] antlerParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] antlerParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.operatorWhile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorWhile([NotNull] antlerParser.OperatorWhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.operatorWhile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorWhile([NotNull] antlerParser.OperatorWhileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.stmtList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtList([NotNull] antlerParser.StmtListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.stmtList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtList([NotNull] antlerParser.StmtListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] antlerParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] antlerParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.assignStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignStmt([NotNull] antlerParser.AssignStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.assignStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignStmt([NotNull] antlerParser.AssignStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.assignOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignOp([NotNull] antlerParser.AssignOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.assignOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignOp([NotNull] antlerParser.AssignOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.logicalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalExpr([NotNull] antlerParser.LogicalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.logicalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalExpr([NotNull] antlerParser.LogicalExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExpr([NotNull] antlerParser.OrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.orExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExpr([NotNull] antlerParser.OrExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.orTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrTail([NotNull] antlerParser.OrTailContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.orTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrTail([NotNull] antlerParser.OrTailContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] antlerParser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] antlerParser.AndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.andTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndTail([NotNull] antlerParser.AndTailContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.andTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndTail([NotNull] antlerParser.AndTailContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.relExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelExpr([NotNull] antlerParser.RelExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.relExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelExpr([NotNull] antlerParser.RelExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.relTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelTail([NotNull] antlerParser.RelTailContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.relTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelTail([NotNull] antlerParser.RelTailContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.relOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelOp([NotNull] antlerParser.RelOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.relOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelOp([NotNull] antlerParser.RelOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.addExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddExpr([NotNull] antlerParser.AddExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.addExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddExpr([NotNull] antlerParser.AddExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.addTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddTail([NotNull] antlerParser.AddTailContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.addTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddTail([NotNull] antlerParser.AddTailContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.mulExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulExpr([NotNull] antlerParser.MulExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.mulExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulExpr([NotNull] antlerParser.MulExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.mulTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulTail([NotNull] antlerParser.MulTailContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.mulTail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulTail([NotNull] antlerParser.MulTailContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] antlerParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] antlerParser.FactorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
