//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from antler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="antlerParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IantlerListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] antlerParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] antlerParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.operatorWhile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorWhile([NotNull] antlerParser.OperatorWhileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.operatorWhile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorWhile([NotNull] antlerParser.OperatorWhileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.stmtList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmtList([NotNull] antlerParser.StmtListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.stmtList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmtList([NotNull] antlerParser.StmtListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] antlerParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] antlerParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.assignStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignStmt([NotNull] antlerParser.AssignStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.assignStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignStmt([NotNull] antlerParser.AssignStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.assignOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignOp([NotNull] antlerParser.AssignOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.assignOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignOp([NotNull] antlerParser.AssignOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.logicalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalExpr([NotNull] antlerParser.LogicalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.logicalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalExpr([NotNull] antlerParser.LogicalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] antlerParser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] antlerParser.OrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.orTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrTail([NotNull] antlerParser.OrTailContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.orTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrTail([NotNull] antlerParser.OrTailContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] antlerParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] antlerParser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.andTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndTail([NotNull] antlerParser.AndTailContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.andTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndTail([NotNull] antlerParser.AndTailContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.relExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelExpr([NotNull] antlerParser.RelExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.relExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelExpr([NotNull] antlerParser.RelExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.relTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelTail([NotNull] antlerParser.RelTailContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.relTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelTail([NotNull] antlerParser.RelTailContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelOp([NotNull] antlerParser.RelOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.relOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelOp([NotNull] antlerParser.RelOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.addExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddExpr([NotNull] antlerParser.AddExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.addExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddExpr([NotNull] antlerParser.AddExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.addTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddTail([NotNull] antlerParser.AddTailContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.addTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddTail([NotNull] antlerParser.AddTailContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.mulExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulExpr([NotNull] antlerParser.MulExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.mulExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulExpr([NotNull] antlerParser.MulExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.mulTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulTail([NotNull] antlerParser.MulTailContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.mulTail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulTail([NotNull] antlerParser.MulTailContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] antlerParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] antlerParser.FactorContext context);
}
