//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Antler/antler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IantlerListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class antlerBaseListener : IantlerListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] antlerParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] antlerParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.whileStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStmt([NotNull] antlerParser.WhileStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.whileStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStmt([NotNull] antlerParser.WhileStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.logicalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalExpr([NotNull] antlerParser.LogicalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.logicalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalExpr([NotNull] antlerParser.LogicalExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.disjunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisjunction([NotNull] antlerParser.DisjunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.disjunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisjunction([NotNull] antlerParser.DisjunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.conjunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConjunction([NotNull] antlerParser.ConjunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.conjunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConjunction([NotNull] antlerParser.ConjunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.negation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegation([NotNull] antlerParser.NegationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.negation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegation([NotNull] antlerParser.NegationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] antlerParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] antlerParser.PrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison([NotNull] antlerParser.ComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison([NotNull] antlerParser.ComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.cmpOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmpOp([NotNull] antlerParser.CmpOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.cmpOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmpOp([NotNull] antlerParser.CmpOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] antlerParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] antlerParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.stmtList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtList([NotNull] antlerParser.StmtListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.stmtList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtList([NotNull] antlerParser.StmtListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] antlerParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] antlerParser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.assignmentStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentStmt([NotNull] antlerParser.AssignmentStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.assignmentStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentStmt([NotNull] antlerParser.AssignmentStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="antlerParser.assignOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignOp([NotNull] antlerParser.AssignOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="antlerParser.assignOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignOp([NotNull] antlerParser.AssignOpContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
