//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Antler/antler.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class antlerLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WHILE=1, NOT=2, AND=3, OR=4, GT=5, LT=6, GE=7, LE=8, EQ=9, NE=10, ASSIGN=11, 
		PLUS_ASSIGN=12, MINUS_ASSIGN=13, MULT_ASSIGN=14, DIV_ASSIGN=15, COLON=16, 
		SEMI=17, LPAREN=18, RPAREN=19, IDENTIFIER=20, NUMBER=21, WS=22;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"WHILE", "NOT", "AND", "OR", "GT", "LT", "GE", "LE", "EQ", "NE", "ASSIGN", 
		"PLUS_ASSIGN", "MINUS_ASSIGN", "MULT_ASSIGN", "DIV_ASSIGN", "COLON", "SEMI", 
		"LPAREN", "RPAREN", "IDENTIFIER", "NUMBER", "WS"
	};


	public antlerLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public antlerLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'while'", "'not'", "'and'", "'or'", "'>'", "'<'", "'>='", "'<='", 
		"'=='", "'!='", "'='", "'+='", "'-='", "'*='", "'/='", "':'", "';'", "'('", 
		"')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WHILE", "NOT", "AND", "OR", "GT", "LT", "GE", "LE", "EQ", "NE", 
		"ASSIGN", "PLUS_ASSIGN", "MINUS_ASSIGN", "MULT_ASSIGN", "DIV_ASSIGN", 
		"COLON", "SEMI", "LPAREN", "RPAREN", "IDENTIFIER", "NUMBER", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "antler.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static antlerLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,22,119,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,
		6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,
		7,14,2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,
		7,21,1,0,1,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,2,1,2,1,2,1,2,1,3,1,3,1,
		3,1,4,1,4,1,5,1,5,1,6,1,6,1,6,1,7,1,7,1,7,1,8,1,8,1,8,1,9,1,9,1,9,1,10,
		1,10,1,11,1,11,1,11,1,12,1,12,1,12,1,13,1,13,1,13,1,14,1,14,1,14,1,15,
		1,15,1,16,1,16,1,17,1,17,1,18,1,18,1,19,1,19,5,19,103,8,19,10,19,12,19,
		106,9,19,1,20,4,20,109,8,20,11,20,12,20,110,1,21,4,21,114,8,21,11,21,12,
		21,115,1,21,1,21,0,0,22,1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,8,17,9,19,10,
		21,11,23,12,25,13,27,14,29,15,31,16,33,17,35,18,37,19,39,20,41,21,43,22,
		1,0,4,3,0,65,90,95,95,97,122,4,0,48,57,65,90,95,95,97,122,1,0,48,57,3,
		0,9,10,13,13,32,32,121,0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,
		0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,0,17,1,0,0,0,0,19,1,
		0,0,0,0,21,1,0,0,0,0,23,1,0,0,0,0,25,1,0,0,0,0,27,1,0,0,0,0,29,1,0,0,0,
		0,31,1,0,0,0,0,33,1,0,0,0,0,35,1,0,0,0,0,37,1,0,0,0,0,39,1,0,0,0,0,41,
		1,0,0,0,0,43,1,0,0,0,1,45,1,0,0,0,3,51,1,0,0,0,5,55,1,0,0,0,7,59,1,0,0,
		0,9,62,1,0,0,0,11,64,1,0,0,0,13,66,1,0,0,0,15,69,1,0,0,0,17,72,1,0,0,0,
		19,75,1,0,0,0,21,78,1,0,0,0,23,80,1,0,0,0,25,83,1,0,0,0,27,86,1,0,0,0,
		29,89,1,0,0,0,31,92,1,0,0,0,33,94,1,0,0,0,35,96,1,0,0,0,37,98,1,0,0,0,
		39,100,1,0,0,0,41,108,1,0,0,0,43,113,1,0,0,0,45,46,5,119,0,0,46,47,5,104,
		0,0,47,48,5,105,0,0,48,49,5,108,0,0,49,50,5,101,0,0,50,2,1,0,0,0,51,52,
		5,110,0,0,52,53,5,111,0,0,53,54,5,116,0,0,54,4,1,0,0,0,55,56,5,97,0,0,
		56,57,5,110,0,0,57,58,5,100,0,0,58,6,1,0,0,0,59,60,5,111,0,0,60,61,5,114,
		0,0,61,8,1,0,0,0,62,63,5,62,0,0,63,10,1,0,0,0,64,65,5,60,0,0,65,12,1,0,
		0,0,66,67,5,62,0,0,67,68,5,61,0,0,68,14,1,0,0,0,69,70,5,60,0,0,70,71,5,
		61,0,0,71,16,1,0,0,0,72,73,5,61,0,0,73,74,5,61,0,0,74,18,1,0,0,0,75,76,
		5,33,0,0,76,77,5,61,0,0,77,20,1,0,0,0,78,79,5,61,0,0,79,22,1,0,0,0,80,
		81,5,43,0,0,81,82,5,61,0,0,82,24,1,0,0,0,83,84,5,45,0,0,84,85,5,61,0,0,
		85,26,1,0,0,0,86,87,5,42,0,0,87,88,5,61,0,0,88,28,1,0,0,0,89,90,5,47,0,
		0,90,91,5,61,0,0,91,30,1,0,0,0,92,93,5,58,0,0,93,32,1,0,0,0,94,95,5,59,
		0,0,95,34,1,0,0,0,96,97,5,40,0,0,97,36,1,0,0,0,98,99,5,41,0,0,99,38,1,
		0,0,0,100,104,7,0,0,0,101,103,7,1,0,0,102,101,1,0,0,0,103,106,1,0,0,0,
		104,102,1,0,0,0,104,105,1,0,0,0,105,40,1,0,0,0,106,104,1,0,0,0,107,109,
		7,2,0,0,108,107,1,0,0,0,109,110,1,0,0,0,110,108,1,0,0,0,110,111,1,0,0,
		0,111,42,1,0,0,0,112,114,7,3,0,0,113,112,1,0,0,0,114,115,1,0,0,0,115,113,
		1,0,0,0,115,116,1,0,0,0,116,117,1,0,0,0,117,118,6,21,0,0,118,44,1,0,0,
		0,4,0,104,110,115,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
